Recommendations service performance improvement
aws-samples/retail-demo-store pull request #100
Opened 2020-10-24 18:50 UTC by james-jory

*Description of changes:*

There has been a recent significant jump in latency to some of the resources in the Recommendations service. This seems to be tied to the Optimizely integration when Optimizely is not configured. Since all of the recommendations calls check for an active experiment for the feature and Optimizely is part of the logic path, something in the Optimizely library must be doing some slow-running checking when it's in this non-configured state. Added logic to only check for an Optimizely experiment when Optimizely is configured in the Retail Demo Store deployment.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-26 17:37 UTC, yeeland requested changes

2020-10-26 17:37 UTC, yeeland commented on src/recommendations/src/recommendations-service/experimentation/experiment_manager.py
> +        if self.is_optimizey_configured():
```suggestion
        if self.is_optimizely_configured():
```

2020-10-26 17:37 UTC, yeeland commented on src/recommendations/src/recommendations-service/experimentation/experiment_manager.py
> +    def is_optimizey_configured(self):
```suggestion
    def is_optimizely_configured(self):
```

2020-10-26 18:11 UTC, yeeland approved these changes

2020-10-27 05:20 UTC, manbearshark approved these changes
LGTM

2020-10-27 07:39 UTC, merged