Move .env to template.env
aws-samples/retail-demo-store pull request #261
Opened 2021-08-18 11:49 UTC by damiendaemon

This is a convenience for developers. When developing and switching between branches it becomes easy to accidentally check in `.env` since there is a template `.env` file checked in.
Here we ignore `.env` and instead check in a file called `template.env`.
We do this for the **docker-compose** `.env` and for the **web-ui**.

-----
This work was done by the Dae.mn Team. http://dae.mn/ml
Damien.Duff@dae.mn Joe.Major@dae.mn Kyle.Redelinghuys@dae.mn

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-19 22:35 UTC, james-jory requested changes
The current approach and the proposed change each have their pros and cons. The .env files are intended to provide suitable defaults that you can run with without having to copy them from a template file. With this change you'd have to copy the template before running locally but it does provide more protection against the unintended commit.

I'm okay with switching to this approach but would ask that the template file name be changed to `.env.template` so it will be more easily found by a developer looking for a `.env` file when it doesn't exist to start with.

2021-08-23 19:57 UTC, damiendaemon commented
`template.env` is now `.env.template`. In retrospect perhaps this would have been better as `.template.env` so that editors can pick the file type from the file extension. Happy to make that change if requested.

2021-08-23 20:03 UTC, james-jory requested changes
Minor typo. Otherwise looks good.

2021-08-23 20:03 UTC, james-jory commented on src/web-ui/README.md
> +6. Open your local `.env` file and paste over the top of the lines you selected. Tthere is already a [.env.template](.env.template) file with examples of what this would look like.
Typo. "Tthere" s/b "There".

2021-08-23 20:06 UTC, damiendaemon commented on src/web-ui/README.md
> +6. Open your local `.env` file and paste over the top of the lines you selected. Tthere is already a [.env.template](.env.template) file with examples of what this would look like.
The typo is fixed. Thanks!

2021-08-23 21:14 UTC, james-jory approved these changes
Looks good. Thanks!

2021-08-23 21:14 UTC, merged